### ISSUE TITLE
Unexpected variables when using an external database

### ISSUE THREAD

**Issue by deggy9** [protecode-sc/helm-chart#4]
I want to emphasize that there are typos in the variables. This manifests itself when using an external database.
https://github.com/protecode-sc/helm-chart/blob/c2add4760d4c6de5d566f6409a32ef4a24a02ab1/values.yaml#L11-L13

Variables **postgresqlUsername**, **postgresqlPort**, **postgresqlHost** in templates
https://github.com/protecode-sc/helm-chart/blob/c2add4760d4c6de5d566f6409a32ef4a24a02ab1/templates/configmap-services.yaml#L10-L14
https://github.com/protecode-sc/helm-chart/blob/c2add4760d4c6de5d566f6409a32ef4a24a02ab1/templates/configmap-services.yaml#L23

**Comment by ahayrynen** [comment]
[bdba-2022.3.0 09fb7cd] fix typos in values.yaml
[bdba-2022.3.0 8895670] another typo fix
