### ISSUE TITLE
Blackduck Binary Analysis fail to connect to LDAP Active Directory Server

### ISSUE THREAD

**Issue by iftekharulhoque** [protecode-sc/helm-chart#6]
Over the past 1 month, we tried many different LDAP configuration in file (https://github.com/protecode-sc/helm-chart/blob/master/values.yaml) but still failing to connect to our Active Directory Server.

At this time, we believe this a Bug in Blackduck Binary Analysis system.

**Comment by ahayrynen** [comment]
The fix for this will be available on next image release. It did not correctly work if LDAP required service authentication first.
